(function(global){
  'use strict';
  const encoder = new TextEncoder(), decoder = new TextDecoder('utf-8', {fatal:true});
  const MAX_SITE = 256 * 1024, MAX_FILES = 256, CHUNK = 160;
  function bytes(value){return value instanceof Uint8Array ? value : new Uint8Array(value);}
  function concat(parts){let n=0;for(const p of parts)n+=p.length;const out=new Uint8Array(n);let i=0;for(const p of parts){out.set(p,i);i+=p.length;}return out;}
  function u16(b,i){return b[i]|b[i+1]<<8;}
  function u32(b,i){return (b[i]|b[i+1]<<8|b[i+2]<<16|b[i+3]<<24)>>>0;}
  function put16(b,i,v){b[i]=v&255;b[i+1]=v>>>8&255;}
  function put32(b,i,v){put16(b,i,v);put16(b,i+2,v>>>16);}
  function crc32(data){let c=0xffffffff;for(const x of data){c^=x;for(let k=0;k<8;k++)c=(c>>>1)^(c&1?0xedb88320:0);}return(c^0xffffffff)>>>0;}
  function fcs(data){let c=0xffff;for(const x of data){c^=x;for(let k=0;k<8;k++)c=(c>>>1)^(c&1?0x8408:0);}return(c^0xffff)&65535;}
  function safePath(path){if(typeof path!=='string'||!path||path.includes('\\')||path.startsWith('/')||path.includes('\0')||/^[a-z]+:/i.test(path))return null;const p=path.split('/');if(p.some(s=>!s||s==='.'||s==='..'||/[\x00-\x1f]/.test(s)))return null;return path;}
  function resolvePath(base,ref){if(!ref||/^[a-z][a-z0-9+.-]*:/i.test(ref)||ref.startsWith('//')||ref.startsWith('/')||ref.startsWith('#')||ref.includes('\\'))return null;let clean=ref.split(/[?#]/)[0];try{clean=decodeURIComponent(clean);}catch{return null;}if(!clean)return null;const parts=base.split('/').slice(0,-1);for(const s of clean.split('/')){if(s==='..'){if(!parts.length)return null;parts.pop();}else if(s&&s!=='.')parts.push(s);}return safePath(parts.join('/'));}
  function importHtml(html,name='index.html'){const path=safePath(name);if(!path||!/\.html?$/i.test(path))throw Error('Choose an HTML file with a safe name.');const data=typeof html==='string'?encoder.encode(html):bytes(html);if(data.length>MAX_SITE)throw Error('Page exceeds 256 KiB.');return {entry:path,files:[{path,bytes:data}]};}
  function inflateRaw(input,expected){
    let pos=0,bit=0,out=new Uint8Array(expected),at=0;
    function read(n){let v=0;for(let i=0;i<n;i++){if(pos>=input.length)throw Error('Truncated DEFLATE stream.');v|=((input[pos]>>>bit)&1)<<i;if(++bit===8){bit=0;pos++;}}return v;}
    function table(lengths){const counts=new Uint16Array(16),next=new Uint16Array(16),map=new Map();for(const l of lengths)if(l)counts[l]++;let code=0;for(let n=1;n<=15;n++){code=(code+counts[n-1])<<1;next[n]=code;}for(let sym=0;sym<lengths.length;sym++){const n=lengths[sym];if(!n)continue;let c=next[n]++,rev=0;for(let j=0;j<n;j++){rev=rev<<1|(c&1);c>>>=1;}map.set(n*65536+rev,sym);}return map;}
    function symbol(map){let c=0;for(let n=1;n<=15;n++){c|=read(1)<<(n-1);const s=map.get(n*65536+c);if(s!==undefined)return s;}throw Error('Invalid DEFLATE code.');}
    const lenBase=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258];
    const lenExtra=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0];
    const distBase=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577];
    const distExtra=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];
    let last=0;while(!last){last=read(1);const kind=read(2);if(kind===0){if(bit){bit=0;pos++;}const n=read(16),inv=read(16);if((n^inv)!==65535||at+n>expected)throw Error('Invalid ZIP block.');for(let i=0;i<n;i++)out[at++]=read(8);continue;}
      if(kind===3)throw Error('Invalid DEFLATE block.');let lit,dist;
      if(kind===1){lit=table(Array.from({length:288},(_,i)=>i<144?8:i<256?9:i<280?7:8));dist=table(Array(32).fill(5));}
      else{const hlit=read(5)+257,hdist=read(5)+1,hclen=read(4)+4,order=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],cl=Array(19).fill(0);for(let i=0;i<hclen;i++)cl[order[i]]=read(3);const ct=table(cl),all=[];while(all.length<hlit+hdist){const s=symbol(ct);if(s<16)all.push(s);else{const count=s===16?read(2)+3:s===17?read(3)+3:read(7)+11;const value=s===16?all[all.length-1]:0;if(value===undefined)throw Error('Invalid repeat code.');for(let i=0;i<count;i++)all.push(value);}}if(all.length!==hlit+hdist)throw Error('Invalid Huffman lengths.');lit=table(all.slice(0,hlit));dist=table(all.slice(hlit));}
      for(;;){const s=symbol(lit);if(s<256){if(at>=expected)throw Error('ZIP file exceeds declared size.');out[at++]=s;}else if(s===256)break;else{const ix=s-257;if(ix<0||ix>=lenBase.length)throw Error('Invalid length code.');const n=lenBase[ix]+read(lenExtra[ix]),d=symbol(dist);if(d>=distBase.length)throw Error('Invalid distance code.');const back=distBase[d]+read(distExtra[d]);if(back>at||at+n>expected)throw Error('Invalid ZIP back reference.');for(let i=0;i<n;i++)out[at]=out[at++-back];}}
    }if(at!==expected)throw Error('ZIP file size mismatch.');return out;
  }
  async function importZip(input){const b=bytes(input);if(b.length>MAX_SITE*2)throw Error('ZIP exceeds compressed size limit.');let end=-1;for(let i=b.length-22;i>=Math.max(0,b.length-65557);i--)if(u32(b,i)===0x06054b50){end=i;break;}if(end<0)throw Error('ZIP directory missing.');const count=u16(b,end+10),size=u32(b,end+12),start=u32(b,end+16);if(count>MAX_FILES||start+size>b.length)throw Error('ZIP directory is invalid or too large.');let p=start,total=0;const files=[];for(let i=0;i<count;i++){
      if(u32(b,p)!==0x02014b50||p+46>b.length)throw Error('Invalid ZIP entry.');const flags=u16(b,p+8),method=u16(b,p+10),crc=u32(b,p+16),packed=u32(b,p+20),unpacked=u32(b,p+24),nl=u16(b,p+28),extra=u16(b,p+30),comment=u16(b,p+32),off=u32(b,p+42);if(p+46+nl+extra+comment>b.length)throw Error('Truncated ZIP directory.');const name=decoder.decode(b.subarray(p+46,p+46+nl));p+=46+nl+extra+comment;if(name.endsWith('/'))continue;
      const path=safePath(name);if(!path)throw Error('Unsafe ZIP path: '+name);if(flags&1||![0,8].includes(method))throw Error('Unsupported encrypted or compressed ZIP entry.');if(unpacked>MAX_SITE||total+unpacked>MAX_SITE)throw Error('ZIP exceeds 256 KiB unpacked.');if(u32(b,off)!==0x04034b50||off+30>b.length)throw Error('Invalid ZIP local header.');const dataAt=off+30+u16(b,off+26)+u16(b,off+28);if(dataAt+packed>b.length)throw Error('Truncated ZIP data.');const data=method===0?b.slice(dataAt,dataAt+packed):inflateRaw(b.subarray(dataAt,dataAt+packed),unpacked);if(data.length!==unpacked||crc32(data)!==crc)throw Error('ZIP checksum mismatch.');files.push({path,bytes:data});total+=unpacked;
    }if(!files.length)throw Error('ZIP has no files.');let prefix=files[0].path.split('/')[0]+'/';if(files.every(f=>f.path.startsWith(prefix)))for(const f of files)f.path=f.path.slice(prefix.length);if(new Set(files.map(f=>f.path)).size!==files.length)throw Error('Duplicate ZIP paths.');const pages=files.filter(f=>/\.html?$/i.test(f.path));if(!pages.length)throw Error('ZIP has no HTML page.');const entry=pages.find(f=>/^index\.html?$/i.test(f.path))?.path||pages.find(f=>/(^|\/)index\.html?$/i.test(f.path))?.path||pages[0].path;return {entry,files};
  }
  function packSite(site){if(!site||!safePath(site.entry)||!Array.isArray(site.files)||site.files.length<1||site.files.length>MAX_FILES)throw Error('Invalid site.');const names=new Set(),manifest=[],parts=[];let offset=0;for(const f of site.files){if(!safePath(f.path)||names.has(f.path))throw Error('Invalid or duplicate file path.');names.add(f.path);const data=bytes(f.bytes);manifest.push({path:f.path,size:data.length,offset,crc:crc32(data)});parts.push(data);offset+=data.length;}if(!names.has(site.entry))throw Error('Entry page is missing.');const m=encoder.encode(JSON.stringify({version:1,entry:site.entry,files:manifest}));if(m.length+offset+4>MAX_SITE)throw Error('Site exceeds 256 KiB including manifest.');const head=new Uint8Array(4);put32(head,0,m.length);return concat([head,m,...parts]);}
  function unpackSite(b){b=bytes(b);if(b.length<4||b.length>MAX_SITE)throw Error('Invalid site size.');const n=u32(b,0);if(n>b.length-4||n>65536)throw Error('Invalid manifest size.');const m=JSON.parse(decoder.decode(b.subarray(4,4+n)));if(m.version!==1||!safePath(m.entry)||!Array.isArray(m.files)||m.files.length>MAX_FILES)throw Error('Invalid manifest.');const files=[],names=new Set(),body=b.subarray(4+n);for(const f of m.files){if(!safePath(f.path)||names.has(f.path)||!Number.isInteger(f.offset)||!Number.isInteger(f.size)||f.offset<0||f.size<0||f.offset+f.size>body.length)throw Error('Invalid file record.');names.add(f.path);const data=body.slice(f.offset,f.offset+f.size);if(crc32(data)!==f.crc)throw Error('File checksum mismatch.');files.push({path:f.path,bytes:data});}if(!names.has(m.entry))throw Error('Entry page missing.');return {entry:m.entry,files};}
  function address(call,last){const out=new Uint8Array(7);for(let i=0;i<6;i++)out[i]=(call.padEnd(6,' ')[i].charCodeAt(0)<<1)&255;out[6]=0x60|(last?1:0);return out;}
  const addr=concat([address('APOCAL',false),address('WEB',true)]);
  function createFrame(payload){payload=bytes(payload);if(payload.length>256)throw Error('AX.25 payload too large.');const body=concat([addr,Uint8Array.of(3,0xf0),payload]),out=new Uint8Array(body.length+2);out.set(body);put16(out,body.length,fcs(body));return out;}
  function parseFrame(frame){frame=bytes(frame);if(frame.length<18||frame.length>274||frame[14]!==3||frame[15]!==0xf0||!(frame[13]&1))return null;if(fcs(frame.subarray(0,-2))!==u16(frame,frame.length-2))return null;return frame.slice(16,-2);}
  function rawBits(frame){const out=[];let ones=0;for(const byte of frame)for(let k=0;k<8;k++){const bit=byte>>k&1;out.push(bit);if(bit){if(++ones===5){out.push(0);ones=0;}}else ones=0;}return out;}
  const flag=[0,1,1,1,1,1,1,0];
  function frameBits(frame){const out=[];for(let i=0;i<12;i++)out.push(...flag);out.push(...rawBits(frame),...flag,...flag);return Uint8Array.from(out);}
  function bitsToFrames(bits){const frames=[];let start=-1;for(let i=0;i<=bits.length-8;i++){let yes=true;for(let k=0;k<8;k++)if(bits[i+k]!==flag[k]){yes=false;break;}if(!yes)continue;if(start>=0&&i>start){const stuffed=bits.slice(start,i),data=[],out=[];let ones=0,bad=false;for(let j=0;j<stuffed.length;j++){const bit=stuffed[j];if(ones===5){if(bit!==0){bad=true;break;}ones=0;continue;}data.push(bit);ones=bit?ones+1:0;}if(!bad&&data.length%8===0&&data.length>=18*8&&data.length<=274*8){for(let j=0;j<data.length;j+=8){let v=0;for(let k=0;k<8;k++)v|=data[j+k]<<k;out.push(v);}const b=Uint8Array.from(out);if(parseFrame(b))frames.push(b);}}start=i+8;i+=7;}return frames;}
  function makeTransfer(site,id){const packed=packSite(site),total=Math.ceil(packed.length/CHUNK);if(total>65535)throw Error('Too many chunks.');const frames=[];for(let i=0;i<total;i++){const part=packed.subarray(i*CHUNK,(i+1)*CHUNK),p=new Uint8Array(20+part.length);p.set(encoder.encode('APW1'));put32(p,4,id>>>0);put16(p,8,total);put16(p,10,i);put32(p,12,packed.length);put32(p,16,crc32(part));p.set(part,20);frames.push(createFrame(p));}return frames;}
  function safeBasename(name){return typeof name==='string'&&name.length>0&&encoder.encode(name).length<=255&&name!=='.'&&name!=='..'&&!/[\\/\x00-\x1f\x7f]/.test(name)&&!/^\s+$/.test(name)&&!/[. ]$/.test(name)&&!/^[a-z]:/i.test(name)?name:null;}
  function validType(type){return typeof type==='string'&&type.length<=127&&(!type||/^[a-z0-9][a-z0-9!#$&^_.+-]*\/[a-z0-9][a-z0-9!#$&^_.+-]*(?:;[\x20-\x7e]{1,80})?$/i.test(type));}
  function packFile(file){if(!file||!safeBasename(file.name)||!validType(file.type||''))throw Error('Invalid file metadata.');const data=bytes(file.bytes),meta=encoder.encode(JSON.stringify({version:1,name:file.name,type:file.type||'',size:data.length,crc:crc32(data)}));if(meta.length>4096||data.length+meta.length+4>MAX_SITE)throw Error('File exceeds 256 KiB packed transfer limit.');const head=new Uint8Array(4);put32(head,0,meta.length);return concat([head,meta,data]);}
  function unpackFile(input){const b=bytes(input);if(b.length<6||b.length>MAX_SITE)throw Error('Invalid file payload size.');const n=u32(b,0);if(n<2||n>4096||n>b.length-4)throw Error('Invalid file metadata size.');const meta=JSON.parse(decoder.decode(b.subarray(4,4+n))),data=b.subarray(4+n);if(!meta||meta.version!==1||!safeBasename(meta.name)||!validType(meta.type)||!Number.isInteger(meta.size)||meta.size!==data.length||!Number.isInteger(meta.crc)||meta.crc<0||meta.crc>0xffffffff)throw Error('Invalid file metadata.');if(crc32(data)!==meta.crc)throw Error('File checksum mismatch.');return {name:meta.name,type:meta.type,bytes:data.slice()};}
  function makeFileTransfer(file,id){const packed=packFile(file),total=Math.ceil(packed.length/CHUNK),frames=[];for(let i=0;i<total;i++){const part=packed.subarray(i*CHUNK,(i+1)*CHUNK),p=new Uint8Array(20+part.length);p.set(encoder.encode('APF1'));put32(p,4,id>>>0);put16(p,8,total);put16(p,10,i);put32(p,12,packed.length);put32(p,16,crc32(part));p.set(part,20);frames.push(createFrame(p));}return frames;}
  class TransferReceiver{constructor(){this.sessions=new Map();this.site=null;this.active=null;this.completedId=null;}
    acceptFrame(frame){const p=parseFrame(frame);if(!p||p.length<21||String.fromCharCode(...p.subarray(0,4))!=='APW1')return false;const id=u32(p,4),total=u16(p,8),index=u16(p,10),length=u32(p,12),part=p.subarray(20);if(!total||index>=total||length>MAX_SITE||total!==Math.ceil(length/CHUNK)||part.length!==Math.min(CHUNK,length-index*CHUNK)||crc32(part)!==u32(p,16))return false;let s=this.sessions.get(id);if(!s){s={total,length,chunks:new Array(total),received:0};this.sessions.set(id,s);if(this.sessions.size>3)this.sessions.delete(this.sessions.keys().next().value);}if(s.total!==total||s.length!==length)return false;this.active=id;if(!s.chunks[index]){s.chunks[index]=part.slice();s.received++;}if(s.received===total&&this.completedId!==id){try{this.site=unpackSite(concat(s.chunks));this.completedId=id;}catch(e){this.site=null;}}return true;}
    progress(){const s=this.sessions.get(this.active);return {received:s?.received||0,total:s?.total||0,complete:!!this.site};}
  }
  class EnhancedTransferReceiver{
    constructor(){this.sessions=new Map();this.active=null;this.file=null;this.site=null;this.completed=null;}
    acceptFrame(frame){
      const p=parseFrame(frame);if(!p||p.length<21)return false;
      const marker=String.fromCharCode(...p.subarray(0,4));if(marker!=='APF1'&&marker!=='APW1')return false;
      const id=u32(p,4),total=u16(p,8),index=u16(p,10),length=u32(p,12),part=p.subarray(20);
      if(!total||index>=total||length<1||length>MAX_SITE||total!==Math.ceil(length/CHUNK)||part.length!==Math.min(CHUNK,length-index*CHUNK)||crc32(part)!==u32(p,16))return false;
      const key=marker+':'+id;let session=this.sessions.get(key);
      if(!session){session={marker,id,total,length,chunks:new Array(total),received:0,complete:false};this.sessions.set(key,session);if(this.sessions.size>6)this.sessions.delete(this.sessions.keys().next().value);}
      if(session.total!==total||session.length!==length)return false;
      this.active=key;
      if(!session.chunks[index]){session.chunks[index]=part.slice();session.received++;}
      if(session.received===total&&!session.complete){
        try{const packed=concat(session.chunks),value=marker==='APF1'?unpackFile(packed):unpackSite(packed);session.complete=true;if(marker==='APF1')this.file=value;else this.site=value;this.completed={marker,id,kind:marker==='APF1'?'file':'site',value};}
        catch{this.sessions.delete(key);this.active=null;return false;}
      }
      return true;
    }
    progress(){const s=this.sessions.get(this.active);return {received:s?.received||0,total:s?.total||0,complete:!!s?.complete,marker:s?.marker||null,id:s?.id??null};}
  }
  function makeToneBits(frames){const out=[];for(const frame of frames)out.push(...frameBits(frame));return Uint8Array.from(out);}
  class AudioEncoder{constructor(frames,rate,repeat=true){this.bits=makeToneBits(frames);this.rate=rate;this.repeat=repeat;this.bitIndex=0;this.bitTime=0;this.newBit=true;this.tone=1;this.phase=0;this.done=false;}
    fill(out){for(let i=0;i<out.length;i++){if(this.done){out[i]=0;continue;}if(this.newBit){if(this.bits[this.bitIndex]===0)this.tone^=1;this.newBit=false;}out[i]=Math.sin(this.phase*2*Math.PI)*.75;this.phase+= (this.tone?1200:2200)/this.rate;this.phase-=Math.floor(this.phase);this.bitTime+=1200/this.rate;if(this.bitTime>=1){this.bitTime-=1;this.bitIndex++;this.newBit=true;if(this.bitIndex>=this.bits.length){if(this.repeat)this.bitIndex=0;else this.done=true;}}}return out;}
    duration(){return this.bits.length/1200;}
  }
  function encodeAudio(frames,rate){const enc=new AudioEncoder(frames,rate,false),out=new Float32Array(Math.ceil(enc.duration()*rate)+2);enc.fill(out);return out;}
  class AudioDecoder{constructor(rate,onFrame){this.rate=rate;this.onFrame=onFrame;this.bitSamples=rate/1200;this.phaseMark=0;this.phaseSpace=0;this.mi=0;this.mq=0;this.si=0;this.sq=0;this.alpha=1-Math.exp(-1/(rate/1200*.38));this.tone=null;this.clock=0;this.lastTone=1;this.bits=[];this.level=0;this.cooldown=0;}
    feed(samples){let power=0;for(const x of samples){power+=x*x;const a=this.alpha;this.mi+=a*(x*Math.cos(this.phaseMark)-this.mi);this.mq+=a*(x*Math.sin(this.phaseMark)-this.mq);this.si+=a*(x*Math.cos(this.phaseSpace)-this.si);this.sq+=a*(x*Math.sin(this.phaseSpace)-this.sq);this.phaseMark+=2*Math.PI*1200/this.rate;this.phaseSpace+=2*Math.PI*2200/this.rate;if(this.phaseMark>2*Math.PI)this.phaseMark-=2*Math.PI;if(this.phaseSpace>2*Math.PI)this.phaseSpace-=2*Math.PI;const mark=this.mi*this.mi+this.mq*this.mq,space=this.si*this.si+this.sq*this.sq;const tone=mark>space?1:0;if(this.tone===null){this.tone=tone;this.lastTone=tone;}if(tone!==this.tone&&Math.abs(mark-space)>(mark+space)*.16){this.tone=tone;this.clock=this.bitSamples*.23;}
      this.clock++;if(this.clock>=this.bitSamples){this.clock-=this.bitSamples;const bit=this.tone===this.lastTone?1:0;this.lastTone=this.tone;this.bits.push(bit);if(this.bits.length>5000)this.bits.splice(0,this.bits.length-3000);if(this.bits.length%8===0){const found=bitsToFrames(this.bits);for(const frame of found)this.onFrame(frame);if(found.length)this.bits=this.bits.slice(-64);}}
    }this.level=Math.sqrt(power/samples.length);}
  }
  function decodeAudio(samples,rate){const found=[],seen=new Set(),d=new AudioDecoder(rate,f=>{const key=Array.from(f).join(',');if(!seen.has(key)){seen.add(key);found.push(f);}});for(let i=0;i<samples.length;i+=1024)d.feed(samples.subarray(i,i+1024));return found;}
  function previewReferences(site,page){const file=site.files.find(f=>f.path===page);if(!file)return {};const html=decoder.decode(file.bytes),found={};for(const m of html.matchAll(/(?:src|href|poster)\s*=\s*["']([^"']+)["']/gi)){const p=resolvePath(page,m[1]);if(p&&site.files.some(f=>f.path===p))found[m[1]]=p;}return found;}
  global.ApocalypseCore={MAX_SITE,crc32,fcs,safePath,safeBasename,resolvePath,importHtml,importZip,packSite,unpackSite,packFile,unpackFile,createFrame,parseFrame,frameBits,bitsToFrames,makeTransfer,makeFileTransfer,TransferReceiver,EnhancedTransferReceiver,AudioEncoder,AudioDecoder,encodeAudio,decodeAudio,previewReferences};
})(globalThis);
